'use strict';
// Owner-supplied enquiry address; replace when a business mailbox is ready.
const ACE_CONTACT_EMAIL = 'emiliosanchezharris@gmail.com';
const dialogs = document.querySelectorAll('dialog');
document.querySelectorAll('[data-open]').forEach(button => button.addEventListener('click', () => { const dialog = document.getElementById(button.dataset.open); if(dialog) dialog.showModal(); }));
document.querySelectorAll('[data-close]').forEach(button => button.addEventListener('click', () => button.closest('dialog').close()));
dialogs.forEach(dialog => dialog.addEventListener('click', event => { if(event.target === dialog){ const rect=dialog.getBoundingClientRect(); if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom) dialog.close(); }}));
if(ACE_CONTACT_EMAIL){const link=document.getElementById('contact-email');link.hidden=false;link.href=`mailto:${ACE_CONTACT_EMAIL}?subject=${encodeURIComponent('Let’s build something — Ace Agents')}`;link.textContent='Email Emilio ↗';document.getElementById('contact-copy').textContent='Tell me about your business, what you have in mind, and what a good outcome would look like. I’ll take it from there.';document.getElementById('contact-note').textContent='Work directly with Emilio, from the first hello.';}
function updateTime(){document.getElementById('sf-time').textContent=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',hour:'numeric',minute:'2-digit',hour12:true}).format(new Date());}updateTime();setInterval(updateTime,60000);document.getElementById('year').textContent=new Date().getFullYear();
const sections=[...document.querySelectorAll('main>section[id]')];const navLinks=[...document.querySelectorAll('nav a')];if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(a=>{const active=a.hash==='#'+entry.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});});},{rootMargin:'-15% 0px -65% 0px'});sections.forEach(section=>observer.observe(section));}
const scenarios={salon:{lines:[['Ace reception','Thanks for calling Willow Salon. I’m the salon’s AI assistant. How can I help?'],['Caller','Hi! I’m looking for a haircut this Saturday.'],['Ace reception','I can take an appointment request. Are you a new client, and what time would work best?'],['Caller','First time! Sometime after two would be great.'],['Ace reception','Great. I’d collect your name and contact details, then send the request to the salon for confirmation.']],outcome:'The salon receives a structured appointment request. A team member confirms availability; nothing is booked without confirmation.'},home:{lines:[['Ace reception','Thanks for calling Coast Home Services. I’m the team’s AI assistant. What can we help with?'],['Caller','Our kitchen tap has been dripping. Can someone come this week?'],['Ace reception','I can help request a visit. Is it a steady drip, or is water leaking onto the floor?'],['Caller','Just a drip from the tap. No water on the floor.'],['Ace reception','I’d collect your service address, preferred times, and contact details so the team can follow up with availability.']],outcome:'The team receives the issue, requested timing, and callback details. Urgent or uncertain requests can be routed to a person using the business’s rules.'},fitness:{lines:[['Ace reception','Hello, you’ve reached Goodform. I’m the studio’s AI assistant. How can I help?'],['Caller','I’ve never done Pilates. Is there a beginner class?'],['Ace reception','The Foundations class is designed for first-timers. Would you like the team to help you choose a session?'],['Caller','Yes, ideally a weekday morning.'],['Ace reception','I’d take your name and preferred contact method, then ask the studio to follow up with available beginner sessions.']],outcome:'A new lead gets an answer and a clear next step. The studio receives the person’s interest and availability, ready for a personal follow-up.'}};
let currentScenario='salon',lineCount=1;const conversation=document.getElementById('conversation'),nextButton=document.getElementById('next-line');
function addLine(index){const [role,copy]=scenarios[currentScenario].lines[index];const message=document.createElement('div');message.className='message'+(role==='Caller'?' caller':'');const label=document.createElement('small');label.textContent=role.toUpperCase();const text=document.createElement('span');text.textContent=copy;message.append(label,text);conversation.append(message);conversation.scrollTop=conversation.scrollHeight;}
function resetScenario(){lineCount=1;conversation.replaceChildren();addLine(0);document.getElementById('call-progress').textContent='1 of 5';nextButton.textContent='Continue call →';document.getElementById('call-result').hidden=true;}
document.querySelectorAll('[data-scenario]').forEach(button=>button.addEventListener('click',()=>{currentScenario=button.dataset.scenario;document.querySelectorAll('[data-scenario]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});resetScenario();}));
nextButton.addEventListener('click',()=>{if(lineCount>=5){resetScenario();return;}addLine(lineCount);lineCount++;document.getElementById('call-progress').textContent=lineCount+' of 5';if(lineCount===5){nextButton.textContent='Replay example ↺';document.getElementById('call-outcome').textContent=scenarios[currentScenario].outcome;document.getElementById('call-result').hidden=false;}});resetScenario();
