'use strict';
document.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.open).showModal()));
document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}}));
document.querySelectorAll('[data-menu]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-menu]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelectorAll('[data-category]').forEach(item=>item.hidden=button.dataset.menu!=='all'&&item.dataset.category!==button.dataset.menu);}));
document.querySelectorAll('input[type=date]').forEach(input=>{const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());input.min=date.toISOString().slice(0,10);});
document.querySelectorAll('[data-demo-form]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form),output=form.parentElement.querySelector('.demo-result');const name=String(data.get('name')).trim()||'there';if(form.dataset.kind==='reservation'){const date=new Date(String(data.get('date'))+'T12:00:00');output.textContent=`Thanks, ${name}. Sample request: ${data.get('party')} on ${date.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})} at ${data.get('time')}. This is a preview only — no table has been reserved and no request has been sent.`;}else{output.textContent=`Thanks, ${name}. Your sample enquiry about ${String(data.get('project')).toLowerCase()} is ready. On a live site, this would reach the studio. This demo has not sent or saved your details.`;}output.hidden=false;output.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}));
const schedule={mon:[['7:00 am','Foundations','50 min · Reformer','Beginner friendly'],['9:30 am','Everyday Flow','50 min · Reformer','All levels'],['5:30 pm','Slow & Strong','50 min · Mat Pilates','All levels']],tue:[['7:30 am','Everyday Flow','50 min · Reformer','All levels'],['12:00 pm','Lunch Reset','40 min · Mat Pilates','All levels'],['6:00 pm','Foundations','50 min · Reformer','Beginner friendly']],wed:[['7:00 am','Slow & Strong','50 min · Mat Pilates','All levels'],['10:00 am','Foundations','50 min · Reformer','Beginner friendly'],['5:30 pm','Everyday Flow','50 min · Reformer','All levels']],thu:[['8:00 am','Everyday Flow','50 min · Reformer','All levels'],['12:00 pm','Lunch Reset','40 min · Mat Pilates','All levels'],['6:00 pm','Slow & Strong','50 min · Mat Pilates','All levels']],fri:[['7:00 am','Foundations','50 min · Reformer','Beginner friendly'],['9:30 am','Everyday Flow','50 min · Reformer','All levels'],['4:30 pm','Friday Unwind','45 min · Stretch & mobility','All levels']]};
const dayNames={mon:'Monday',tue:'Tuesday',wed:'Wednesday',thu:'Thursday',fri:'Friday'};
function showSchedule(day){const parent=document.getElementById('schedule');if(!parent)return;parent.replaceChildren();schedule[day].forEach(([time,name,description,level])=>{const row=document.createElement('article');row.className='class-row';const clock=document.createElement('time');clock.textContent=time;const group=document.createElement('div'),h=document.createElement('h3'),p=document.createElement('p'),levelTag=document.createElement('span'),button=document.createElement('button');h.textContent=name;p.textContent=description;group.append(h,p);levelTag.className='class-level';levelTag.textContent=level;button.textContent='Preview';button.setAttribute('aria-label',`Preview ${name} on ${dayNames[day]} at ${time}`);button.addEventListener('click',()=>{document.getElementById('class-title').textContent=name;document.getElementById('class-details').textContent=`${dayNames[day]} at ${time} · ${description} · ${level}. A sample class to show how a simple studio booking experience could feel.`;document.getElementById('class-booking').showModal();});row.append(clock,group,levelTag,button);parent.append(row);});}
document.querySelectorAll('[data-day]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-day]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});showSchedule(button.dataset.day);}));showSchedule('mon');
